services:
  x2t-bot:
    build: .
    container_name: x2t_telegram_bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./bot_database.sqlite3:/app/bot_database.sqlite3
      - ./downloads:/app/downloads
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
